import { useEffect, useMemo, useState } from "react";
import { api } from "../api";

const blank = { name: "", email: "", department: "Engineering", role: "", status: "Active" };
const departments = ["Engineering", "HR", "Finance", "Design", "Marketing", "Sales"];

export default function Employees() {
  const [employees, setEmployees] = useState([]); const [search, setSearch] = useState(""); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState("");
  const loadEmployees = () => api.employees().then(setEmployees).catch((requestError) => setError(requestError.message));
  useEffect(() => { loadEmployees(); }, []);
  const filtered = useMemo(() => employees.filter((employee) => [employee.name, employee.email, employee.department, employee.role].some((value) => value.toLowerCase().includes(search.toLowerCase()))), [employees, search]);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const save = async (event) => { event.preventDefault(); setError(""); try { if (editingId) await api.updateEmployee(editingId, form); else await api.createEmployee(form); await loadEmployees(); setForm(blank); setEditingId(null); setShowForm(false); } catch (requestError) { setError(requestError.message); } };
  const edit = (employee) => { setForm({ name: employee.name, email: employee.email, department: employee.department, role: employee.role, status: employee.status }); setEditingId(employee.id); setShowForm(true); };
  const remove = async (id) => { if (!window.confirm("Delete this employee?")) return; try { await api.deleteEmployee(id); await loadEmployees(); } catch (requestError) { setError(requestError.message); } };
  return <div><div className="page-header"><div><p className="eyebrow">PEOPLE</p><h1>Employees</h1><p>Manage records stored by the Python API.</p></div><button className="primary-button" onClick={() => { setForm(blank); setEditingId(null); setShowForm(true); }}>+ Add Employee</button></div>{error && <div className="form-error">{error}</div>}
    {showForm && <form className="panel employee-form" onSubmit={save}><div className="panel-heading"><div><h2>{editingId ? "Edit Employee" : "Add Employee"}</h2><p>Enter the employee details below.</p></div><button type="button" className="icon-close" onClick={() => setShowForm(false)}>×</button></div><div className="form-grid"><div><label>Full name</label><input name="name" value={form.name} onChange={update} required /></div><div><label>Email</label><input type="email" name="email" value={form.email} onChange={update} required /></div><div><label>Department</label><select name="department" value={form.department} onChange={update}>{departments.map((department) => <option key={department}>{department}</option>)}</select></div><div><label>Role</label><input name="role" value={form.role} onChange={update} required /></div><div><label>Status</label><select name="status" value={form.status} onChange={update}><option>Active</option><option>On Leave</option></select></div></div><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary-button">{editingId ? "Update Employee" : "Save Employee"}</button></div></form>}
    <section className="panel"><div className="toolbar"><div><h2>Employee List</h2><p>{filtered.length} employees shown</p></div><input className="search-input" placeholder="Search employees..." value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Employee</th><th>Department</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((employee) => <tr key={employee.id}><td>#{employee.id}</td><td><div className="employee-cell"><span className="avatar">{employee.name.charAt(0)}</span><div><strong>{employee.name}</strong><small>{employee.email}</small></div></div></td><td>{employee.department}</td><td>{employee.role}</td><td><span className={`status ${employee.status === "Active" ? "active-status" : "leave-status"}`}>{employee.status}</span></td><td><div className="action-buttons"><button onClick={() => edit(employee)}>Edit</button><button className="danger" onClick={() => remove(employee.id)}>Delete</button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state">No employees found.</div>}</div></section></div>;
}
