apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "frontend-name" . }}-deployment 
  namespace: {{ include "frontend-namespace" . }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- range $key, $value := .Values.selectorLabels }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "frontend-name" . }}-container 
          {{- with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "frontend-name" . }}-configmap
            - secretRef:
                name: {{ include "frontend-name" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12  }}
          readinessProbe:
            {{- toYaml .Values.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.liveness | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startup | nindent 12 }}
          