{{- if .Values.secret.enabled }}
apiVersion: v1 
kind: Secret 
metadata:
  name: {{ include "frontend-name" . }}-secret
  namespace: {{ include "frontend-namespace" . }}
type: {{ .Values.secret.type }}
stringData:
  {{- range $key,$value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

