name: CI-pipeline 
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
        # fetch-depth: 0

      - name: Set-up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Build application
        run: npm run build 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  backend:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout-code 
        uses: actions/checkout@v4 

      - name: set up python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'

      - name: install Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install build 

      - name: Build 
        working-directory: backend/app
        run: python -m build 

      - name: Upload Artifacts 
        uses: actions/upload-artifact@v4 
        with:
          name: python-artifact
          path: backend/app/dist/ 

  docker-image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Checkout-code 
        uses: actions/checkout@v4

      - name: Set Docker image version
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV
      # - name: login to DockerHub 
      #   uses: docker/login-action@v3
      #   with: 
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.Docker_PASSWORD }}

      # AWS login 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Azure Login
      - name: Azure login 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Login to Frontend ACR
        run: |
          az acr login --name ${{ secrets.FRONTEND_ACR }}
    

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      
      - name: Docker Build 
        # run: |
        #   docker build \
        #   -t ${{ secrets.DOCKER_USERNAME }}/frontend-dashboard:${VERSION} \
        #   -f src/Dockerfile \
        #   . 
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/employee-dashboard-frontend:${VERSION} \
            -f src/Dockerfile \
            .
            -t ${{ secrets.FRONTEND_ACR }}.azurecr.io/employee-dashboard-frontend:${VERSION} \
            -F src/Dockerfile \
            . 

      - name: Docker Push 
        if: github.ref == 'refs/heads/main'
        # run: |
        #   docker push ${{ secrets.DOCKER_USERNAME }}/frontend-dashboard:${VERSION}            
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/employee-dashboard-frontend:${VERSION}
          docker push ${{ secrets.FRONTEND_ACR }}.azurecr.io/employee-dashboard-frontend:${VERSION}
  docker-image-backend:
    needs: backend 
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: read 
    steps: 
      - name: Checkout-code 
        uses: actions/checkout@v4 

      - name: Set Docker Version
        run: echo "VERSION=v2.${{ github.run_number }}" >> $GITHUB_ENV 

      # - name: Login Dockerhub 
      #   uses: docker/login-action@v3
      #   with: 
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Amazon ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      - name: login to backend ACR
        run: |
          az acr login --name ${{ secrets.BACKEND_ACR }}

      - name: Docker build 
        # run: |
        #   docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${VERSION} \
        #   -f backend/Dockerfile \
        #   backend 
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/employee-dashboard-backend:${VERSION} \
            -f backend/Dockerfile \
            backend 
            -t ${{ secrets.BACKEND_ACR }}.azurecr.io/employee-dashboard-backend:${VERSION} \
            -f backend/Dockerfile \
            backend 

          
      - name: Docker Push 
        if: github.ref == 'refs/heads/main'
        # run: |
        #   docker push ${{ secrets.DOCKER_USERNAME }}/backend:${VERSION}
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/employee-dashboard-backend:${VERSION}
          docker push ${{ secrets.BACKEND_ACR }}.azurecr.io/employee-dashboard-backend:${VERSION}
